### ISSUE TITLE
Add command: "Inverter Technical Data"

### ISSUE THREAD

**Issue by Waldi80** [ysimonx/node-red-contrib-solaredge-power#5]
Hi, 
is it possible to you, to add this command to your node?

It begins at Page 38 in the SolarEdge documentation.

I've tried it on my own, but my programming skills are too low for this...

Many Thanks!

Regards
Waldemar

**Comment by ysimonx** [comment]
> Hi, is it possible to you, to add this command to your node?
> 
> It begins at Page 38 in the SolarEdge documentation.
> 
> I've tried it on my own, but my programming skills are too low for this...
> 
> Many Thanks!
> 
> Regards Waldemar

Hi Waldemar

I think I can try
please tell me which kind of value you intend to provide for


startTime : The start (date + time) to get inverter data
endTime : The end (date + time) to get inverter data

please ?

**Comment by Waldi80** [comment]
For me it will be great to get the actual values.
Start = now - 10 second
End = now
Don‘t know if this is possible…

**Comment by ysimonx** [comment]
> For me it will be great to get the actual values. Start = now - 10 second End = now Don‘t know if this is possible…

Ok

Thank you ... not sure I will have time today

I will inform you as soon as possible

**Comment by Waldi80** [comment]
Thank you!

If it is possible, it will help me so much to build my heating control flow!
Specially I need the live powerLimit values to control my electrical water heater via shelly's.

**Comment by ysimonx** [comment]
<img width="296" alt="Capture d’écran 2023-07-24 à 11 44 16" src="https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/1449867/7701af2d-94f9-480d-ac13-e50a2b55d184">

You should be able to already pilot your shelly thank to powerConsumption  command  "current power flow" : 
here, i am sending to grid 0.31 kw

I can switch on or off some TP Link smart plug based upon this node

**Comment by Waldi80** [comment]
I know this one.

In my use case I need to know the value of the "powerLimit".

Because of some regulations it is set to max. 70% of the peak Power to grid!
So I will try to get some consumptionion when the system starts to limit the peak power.

**Comment by ysimonx** [comment]
<img width="1016" alt="Capture d’écran 2023-07-24 à 20 51 36" src="https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/1449867/a916c498-6667-441d-bfe7-fc3a7f91e86f">

I managed to scrap something

I had to choose a delay of 5 minutes between start and endtime

I considered, for this test, that only one inverter is installed for this site ... do you plan to use more than 1 inverter for the same API key ?

**Comment by ysimonx** [comment]
@Waldi80 
please, can you test v0.3.3 of
node-red-contrib-solaredge-power
and choose "inverter technical data" as the command please ?

**Comment by Waldi80** [comment]
It works! 

Thank you so much! :-)

![image](https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/140369599/3e8e4103-32fa-444d-9247-f6264b3b4b23)

No, at the moment it will be only one inverter.
And I think 5 minutes will work fine too.

**Comment by ysimonx** [comment]
When I tried less than 5 minutes, no data were often returned ...

**Comment by Waldi80** [comment]
So I have a  delay value for the heater... ;-)
It can switch between 0,5 and 3,5 kW in 0,5kW steps.

So I will try to switch on 0,5kW then wait 5 min. if the power limit will be still active, then switch to 1kW and so on...

till it stays at 100%.

Thank you!

**Comment by ysimonx** [comment]
I have the smart energy for hot water from solaredge at home

this is a fantastic (but expensive) product
<img width="133" alt="Capture d’écran 2023-07-24 à 21 29 09" src="https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/1449867/00c6c6cf-1e44-49b3-ad67-296f5f8791d9">

On sunrise, the energy sent to my heater is exactly the same value than the current that should be sent to the grid ...

**Comment by ysimonx** [comment]
let's keep in touch, i can close the comment :)

**Comment by MausPhyt** [comment]
> <img alt="Capture d’écran 2023-07-24 à 20 51 36" width="1016" src="https://user-images.githubusercontent.com/1449867/255686210-a916c498-6667-441d-bfe7-fc3a7f91e86f.png">
> I managed to scrap something
> 
> I had to choose a delay of 5 minutes between start and endtime
> 
> I considered, for this test, that only one inverter is installed for this site ... do you plan to use more than 1 inverter for the same API key ?

I have a question about this, i have the modules running successfully, however there is a gap in time. i can also see it in your screen printout, the time now in the present in the debug window. and the answer in the API is 2 hours different, also 2 hours older data, i first thought it had to do with UTC time, but it is actually 2 hours in the past, when i call the API in postman and i adjust the time to the same as the answer the data is exactly the same, how can we adjust this to the current time.  
![image](https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/102989975/b1e6a5ab-a88d-40d9-8fb5-49aa415b4fad)

**Comment by ysimonx** [comment]
> > <img alt="Capture d’écran 2023-07-24 à 20 51 36" width="1016" src="https://user-images.githubusercontent.com/1449867/255686210-a916c498-6667-441d-bfe7-fc3a7f91e86f.png">
> > I managed to scrap something
> > I had to choose a delay of 5 minutes between start and endtime
> > I considered, for this test, that only one inverter is installed for this site ... do you plan to use more than 1 inverter for the same API key ?
> 
> I have a question about this, i have the modules running successfully, however there is a gap in time. i can also see it in your screen printout, the time now in the present in the debug window. and the answer in the API is 2 hours different, also 2 hours older data, i first thought it had to do with UTC time, but it is actually 2 hours in the past, when i call the API in postman and i adjust the time to the same as the answer the data is exactly the same, how can we adjust this to the current time. ![image](https://user-images.githubusercontent.com/102989975/271238968-b1e6a5ab-a88d-40d9-8fb5-49aa415b4fad.png)

I Think that it dépends on your location.
The debug Time of debug should be the Time where your nodered instance IS running. 
The inverter Time may be an Universal Time (UTC) ... that you should convert to your localtime. I will verify this as soon as i can

**Comment by MausPhyt** [comment]
Thanks very much for your huge quick response, I made 2 more comparisons , Postman with adjusted times past and now, maybe then you can see directly what could be going wrong, UTC or UTC+1 Amsterdam where I am I think I have ruled out with this. 
![image](https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/102989975/e4a54790-fcde-4d92-a043-d3665d7f3345)

and 

![image](https://github.com/ysimonx/node-red-contrib-solaredge-power/assets/102989975/101743ff-1627-4414-ae27-8eff9f10bdc5)

Also compare the values, I think you can see this yourself with your own node and postman.

greetings Maurice.
